# Generated by Django 3.0.8 on 2020-07-14 02:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='duedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 14, 7, 38, 12, 23082)),
        ),
    ]
