# Generated by Django 3.0.8 on 2020-07-14 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200714_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='duedate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 7, 14, 15, 54, 30, 529464)),
        ),
    ]
