# Generated by Django 3.0.8 on 2020-07-15 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20200715_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='duedate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
